name: Preview branch + Deploy to GitHub Pages

on:
  push:
    branches-ignore:
      - gh-pages

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages-deploy'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create preview branch for this commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          PREVIEW=preview-${{ github.sha }}
          git switch -c "$PREVIEW"
          git push origin HEAD:refs/heads/"$PREVIEW"

      - name: Deploy repository to `gh-pages` branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
